### ISSUE TITLE
Update fourmolu to 0.4.0.0

### ISSUE THREAD

**Issue by xsebek** [restyled-io/restylers#369]
Bumping the Fourmolu version would give us a few features, like the `--cabal-default-extensions` flag to read configuration from the cabal file and avoid copy-pasting it to `.restyled.yaml`.

It should suffice updating [stack.yaml](https://github.com/restyled-io/restylers/blob/main/fourmolu/stack.yaml) to use [19.13 which has the newer Fourmolu version](https://www.stackage.org/lts-19.13/package/fourmolu-0.4.0.0).

I am unsure what changes in the Dockerfile would be needed, probably using GHC9.0?

Do you have any suggestions @TristanCacqueray?

**Comment by pbrisbin** [comment]
Sorry I missed this Issue!

The Haskell builds are a bit tricky because the paths that you copy from the build stage to the run stage are version-dependent. 

The process is to:

1. Update `stack.yaml` as necessary
2. Un-comment [these lines](https://github.com/restyled-io/restylers/blob/main/fourmolu/Dockerfile#L8-L19)
3. [Run a build](https://github.com/restyled-io/restyled.io/wiki/Adding-a-Restyler#2-test-locally) and look at the output (you could also let CI do this step, though that's a lot slower)
4. Update [these lines](https://github.com/restyled-io/restylers/blob/main/fourmolu/Dockerfile#L31-L37) based on that output

Feel free to attempt a PR if you're motivated. Otherwise, I hope to get to it this week.

**Comment by pbrisbin** [comment]
It looks like 0.8.2.0 is latest on Hackage. Any reason to prefer 0.4 instead of going all the way to that?

**Comment by xsebek** [comment]
If I remember correctly it was the smallest upgrade that would give me some options that I wanted.

If we can get a newer version then that is definitely better. 👍

**Comment by pbrisbin** [comment]
Ah, it looks like > 0.4 are building against GHC 9.2. That's a big of a lift since I'd have to move off the latest LTS. stylish-haskell has the same problem in its latest version.

0.4 it is!

**Comment by pbrisbin** [comment]
https://github.com/restyled-io/restylers/pull/386
